#version 460

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba16f, set = 0, binding = 0) uniform image2D targetImage;

layout(push_constant) uniform BackgroundConstants {
    vec4 color;
} background;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(targetImage);
    if (pixel.x < size.x && pixel.y < size.y) {
        imageStore(targetImage, pixel, background.color);
    }
}
